[package]
name = "atrament_session_handshake"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
atrament_diagnostic = { path = "../diagnostic" }
atrament_session_handshake_port = { path = "../session-handshake-port" }

[lib]
path = "application/lib.rs"

[lints]
workspace = true
