allow-comparison-to-zero = false
allow-dbg-in-tests = false
allow-expect-in-consts = false
allow-expect-in-tests = false
allow-indexing-slicing-in-tests = false
allow-mixed-uninlined-format-args = false
allow-one-hash-in-raw-strings = false
allow-panic-in-tests = false
allow-print-in-tests = false
allow-private-module-inception = false
allow-unwrap-in-consts = false
allow-unwrap-in-tests = false
allowed-scripts = ["Latin"]
array-size-threshold = 8192
avoid-breaking-exported-api = false
check-inconsistent-struct-field-initializers = true
cognitive-complexity-threshold = 10
enum-variant-size-threshold = 128
excessive-nesting-threshold = 4
future-size-threshold = 8192
large-error-threshold = 64
lint-commented-code = true
min-ident-chars-threshold = 1
pass-by-value-size-limit = 128
semicolon-inside-block-ignore-singleline = false
single-char-binding-names-threshold = 1
stack-size-threshold = 65536
too-many-arguments-threshold = 4
too-many-lines-threshold = 60
type-complexity-threshold = 100
vec-box-size-threshold = 2048
